$(function(){
	$('#wrap .home').click(function(){
		$('#home').show()
		$('#play').hide()
        $('#studio').hide()
		$('#employee').hide()
        $('#user').hide()
        $('#schedule').hide()
	})
	$('#wrap .play').click(function(){
		$('#play').show()
		$('#home').hide()
        $('#studio').hide()
        $('#employee').hide()
		$('#user').hide()
        $('#schedule').hide()
	})
    $('#wrap .studio').click(function(){
        $('#studio').show()
        $('#home').hide()
        $('#play').hide()
        $('#employee').hide()
        $('#user').hide()
        $('#schedule').hide()
    })
    $('#wrap .employee').click(function(){
        $('#employee').show()
        $('#home').hide()
        $('#play').hide()
        $('#studio').hide()
        $('#user').hide()
        $('#schedule').hide()
    })
    $('#wrap .user').click(function(){
        $('#user').show()
        $('#home').hide()
        $('#play').hide()
        $('#studio').hide()
        $('#employee').hide()
        $('#schedule').hide()
    })
    $('#wrap .schedule').click(function(){
        $('#schedule').show()
        $('#user').hide()
        $('#home').hide()
        $('#play').hide()
        $('#studio').hide()
        $('#employee').hide()
    })
})
